configs:
  logging:
    content: |-
      loglevel.controller: info
        loglevel.creds-init: info
        loglevel.git-init: info
        loglevel.webhook: info
        zap-logger-config: |
          {
            "level": "info",
            "development": false,
            "sampling": {
              "initial": 100,
              "thereafter": 100
            },
            "outputPaths": ["stdout"],
            "errorOutputPaths": ["stderr"],
            "encoding": "json",
            "encoderConfig": {
              "timeKey": "",
              "levelKey": "level",
              "nameKey": "logger",
              "callerKey": "caller",
              "messageKey": "msg",
              "stacktraceKey": "stacktrace",
              "lineEnding": "",
              "levelEncoder": "",
              "timeEncoder": "",
              "durationEncoder": "",
              "callerEncoder": ""
            }
          }
  config-artifact-bucket:
    {}
  config-artifact-pvc:
    {}

services:
  registry:
    image: registry:2
    env:
    - REGISTRY_HTTP_ADDR=0.0.0.0:80
    ports:
    - 80:80/tcp,registry,internal=true
    volumes:
    - storage-registry:/var/lib/registry
  webhook:
    disableServiceMesh: true
    global_permissions:
    - "* gitwatcher.cattle.io/gitwatchers"
    - "* gitwatcher.cattle.io/gitcommits"
    - '* configmaps'
    - '* events'
    - secrets
    image: rancher/gitwatcher:v0.3.1
    args:
    - gitwatcher
    - --listen-address
    - :8090
    imagePullPolicy: always
    ports:
    - 8090/tcp,http-webhookinator
  build-controller:
    global_permissions:
    - '* pods'
    - '* namespaces'
    - '* secrets'
    - '* events'
    - '* serviceaccounts'
    - '* configmaps'
    - '* extentions/deployments'
    - 'create,get,list,watch,patch,update,delete tekton.dev/*'
    - '* apiextensions.k8s.io/customresourcedefinitions'
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:80e040a58ce6c4d58ae893eb934777bce013ef8be079967dc3db783d76fa5aaa
    configs:
    - logging/content:/etc/config-logging
    env:
    - SYSTEM_NAMESPACE=${NAMESPACE}
    args:
    - -logtostderr
    - -stderrthreshold
    - INFO
    - -kubeconfig-writer-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter@sha256:2000fdb77fd830719533756afe246c460949b46eb0c7fc1841de17656d6f5114
    - -creds-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init@sha256:b4877c99d928fad3cf26c995d171674b34d206178d6f9f0efb337ebff01bb34b
    - -git-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:4b91c31560f18a8f09c68d5288f2261797b6df31522a57a9d7350bc0060a1284
    - -nop-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop@sha256:9160ed41b20b2822d06e907d89f6398ea866c86a971f83371efb9e147fba079f
    - -bash-noop-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/bash@sha256:0355a9b21a7c0cc9466bf75071648e266de07b5e13fbfd271ec791c45a818bdb
    - -gsutil-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/gsutil@sha256:6b6b8e02f6f03fb33cf3007b6b501e07bf2f435a0309482b868712a20f1dfd78
    - -entrypoint-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:4d1fe990ca06ecc671370dfeab31d857efa8ccf81d632a672561c60482fd9aae
    - -imagedigest-exporter-image
    - gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256:3d36cb375da0e4b5b5cf8b0964ed3d80f4645142ac609679c3b26a369f3ed340


kubernetes:
  manifest: |-
    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: clustertasks.tekton.dev
    spec:
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: ClusterTask
        plural: clustertasks
      scope: Cluster
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: images.caching.internal.knative.dev
    spec:
      group: caching.internal.knative.dev
      names:
        categories:
        - all
        - knative-internal
        - caching
        kind: Image
        plural: images
        shortNames:
        - img
        singular: image
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: pipelines.tekton.dev
    spec:
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: Pipeline
        plural: pipelines
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: pipelineruns.tekton.dev
    spec:
      additionalPrinterColumns:
      - JSONPath: .status.conditions[?(@.type=="Succeeded")].status
        name: Succeeded
        type: string
      - JSONPath: .status.conditions[?(@.type=="Succeeded")].reason
        name: Reason
        type: string
      - JSONPath: .status.startTime
        name: StartTime
        type: date
      - JSONPath: .status.completionTime
        name: CompletionTime
        type: date
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: PipelineRun
        plural: pipelineruns
        shortNames:
        - pr
        - prs
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: pipelineresources.tekton.dev
    spec:
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: PipelineResource
        plural: pipelineresources
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: tasks.tekton.dev
    spec:
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: Task
        plural: tasks
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1

    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: taskruns.tekton.dev
    spec:
      additionalPrinterColumns:
      - JSONPath: .status.conditions[?(@.type=="Succeeded")].status
        name: Succeeded
        type: string
      - JSONPath: .status.conditions[?(@.type=="Succeeded")].reason
        name: Reason
        type: string
      - JSONPath: .status.startTime
        name: StartTime
        type: date
      - JSONPath: .status.completionTime
        name: CompletionTime
        type: date
      group: tekton.dev
      names:
        categories:
        - all
        - tekton-pipelines
        kind: TaskRun
        plural: taskruns
        shortNames:
        - tr
        - trs
      scope: Namespaced
      subresources:
        status: {}
      version: v1alpha1
    ---
