services:
  cert-manager:
    global_permissions:
    - '* certmanager.k8s.io/*'
    - '* extensions/ingresses'
    - '* configmaps'
    - '* secrets'
    - '* events'
    - '* services'
    - '* pods'
    image: "rancher/cert-manager-controller:${TAG}"
    imagePullPolicy: Always
    args:
    - cert-manager
    - --leader-election-namespace
    - ${NAMESPACE}
    - --cluster-resource-namespace
    - ${NAMESPACE}
    - --acme-http01-solver-image
    - "rancher/cert-manager-acmesolver:${TAG}"
    - --logtostderr
    - "true"

