discovery:
  enabled: false
  
gateway:
  certGenJob:
    enabled: false
  upgrade: false
  validation:
    enabled: false
  deployment:
    stats: false
  readGatewaysFromAllNamespaces: true

gatewayProxies:
  gatewayProxy:
    upgrade: false
    stats: false
    gatewaySettings:
      customHttpGateway:
        virtualServiceNamespaces:
        - "*"
        options:
          httpConnectionManagerSettings:
            useRemoteAddress: true
      customHttpsGateway:
        virtualServiceNamespaces:
        - "*"
        options:
          httpConnectionManagerSettings:
            useRemoteAddress: true

gloo:
  deployment:
    stats: false

namespace:
  create: false

